### ISSUE TITLE
Git clone cmd

### ISSUE THREAD

**Issue by OpenSystemCode** [janoside/lndash#37]
If you use the git clone cmd on 
https://github.com/janoside/lnd-admin#2b-install-lnd-admin-from-source

you get the message :"Please make sure you have the correct access rights
and the repository exist"

Change the cmd: 
`git clone git@github.com:janoside/lnd-admin.git`

to

`git clone https://github.com/janoside/lnd-admin.git `

**Comment by janoside** [comment]
Done.
