### ISSUE TITLE
Feature: Display channel liquidity ratio

### ISSUE THREAD

**Issue by rationalflaneur** [janoside/lndash#38]
**Describe the bug**
In order to run a successful node, it's very important to know which of my channels have insufficient inbound/outbound liquidity, so that I can rebalance them. It would be enormously useful if I could see a simple visualization on the channel screen of a channel's inbound/outbound ratio with a percentage display.

**Environment (please complete the following information):**
 - LND Version: 0.7.0-beta commit=v0.7.0-beta-rc1-50-g2a6f2bbd47d09addbd928b2d29735b6a60dce352
 - LND Admin Version (commit hash if available, otherwise version number) a8bf54ff9afc32b892b3733b2a1485cf011faf1b

**Comment by janoside** [comment]
@rationalflaneur Agreed, that's an important function. On the channel details page (url="/channel/{CHANNEL_ID}") there is already a ratio with percentage shown, like the image below:

<img width="366" alt="Screenshot 2019-06-22 10 38 09" src="https://user-images.githubusercontent.com/99734/59965509-a60d3c00-94fe-11e9-91a3-25e54fcd3cb2.png">

Does that serve the purpose you're hoping for, or would you like that format changed in some way? Is there a different page that you're hoping to have these ratios/percentages added to? If so, let me know which page (by url).

Let me know.

**Comment by rationalflaneur** [comment]
Thanks for the response! The channel page ratio display is useful, but I think it could be much more useful in two ways:

- if the display was available in the channel overview page (/local-channels), so that I could see all my channels and see ratios across channels. This is important because I have to make rebalancing decisions in the context of other channels. For instance, I'll want to make sure some channels to have high inbound liquidity, some with high outbound liquidity, while others are more balanced towards 50-50. Seeing them all together makes this easier.

- I would also request having a visualization, like a bar chart or something similar that makes it easy to scan the percentages. Perhaps something like this:

![ratio](https://user-images.githubusercontent.com/48932639/59965939-ec54a200-94e2-11e9-8047-354314ae57bc.png)

Thanks again for taking the time to respond, `lnd-admin` is a beautiful, powerful tool!

**Comment by janoside** [comment]
This is done in master and pending a release.
