### ISSUE TITLE
Explorer link to bitcoin explorer is dead.

### ISSUE THREAD

**Issue by Jaska8** [janoside/lndash#48]
Hi.
Explorer link seems to be broken, can this explorer be ran locally and what needs to be edited in source code to change the explorer url?

**Comment by janoside** [comment]
Yes, [Bitcoin Explorer](https://github.com/janoside/btc-rpc-explorer) is my open-source explorer and it's definitely meant to be run locally. To configure this tool to link to your explorer, you can configure it in your `.env` file, as shown [here](https://github.com/janoside/lndash/blob/master/.env-sample#L3).
